apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: my-pipeline
spec:
  workspaces:
    - name: shared-data
  params:
  - name: repo-url
    type: string
  - name: revision
    type: string
  tasks:
  - name: fetch-source
    taskRef:
      name: git-clone
    params:
      - name: url
        value: $(params.repo-url)
      - name: revision
        value: $(params.revision)
    workspaces:
      - name: output
        workspace: shared-data
  - name: list-source
    runAfter: ["fetch-source"]
    taskRef:
      name: list-source
    workspaces:
      - name: source
        workspace: shared-data